name: Run Tests & Linting

on:
  push:
    branches: [main, dev, master] # Runs when pushing to main or dev branches
  pull_request:
    branches: [main, dev, master] # Runs on PRs to these branches

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run Ruff Linting
        run: uv run ruff check .

      - name: Run Pytest
        run: uv run  pytest --maxfail=1 --disable-warnings -v
